apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-app
  namespace: stage
  labels:
    app: fb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fb-app
  template:
    metadata:
      labels:
        app: fb-app
    spec:
      containers:
      - image: nginx:1.20
        imagePullPolicy: IfNotPresent
        name: front
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: back
        env:
        - name: HTTP_PORT
          value: "8080"
