apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
  namespace: prod
  labels:
    app: front-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: front
        env:
        - name: HTTP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: front-app-ip
  namespace: prod
spec:
  selector:
    app: front-app
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080