apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-app
  namespace: stage
  labels:
    app: fb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fb-app
  template:
    metadata:
      labels:
        app: fb-app
    spec:
      containers:
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: front
        volumeMounts:
        - mountPath: "/from_back"
          name: static
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: back
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
        volumeMounts:
        - mountPath: "/to_front"
          name: static
      volumes:
      - name: static
        emptyDir: {}